"""
scripts/bundle_reports.py

Collects every HTML report generated by the hackingrongo pipeline, creates
a navigable index.html, and zips the whole bundle for one-click download.

What it does
------------
1.  Scans the entire outputs/ tree for .html files.
2.  Copies them into outputs/reports_bundle/ preserving sub-paths so
    relative links (e.g. passage_reports/index.html → P007_ADHS.html) work.
3.  Writes outputs/reports_bundle/index.html — a dark-terminal landing page
    that organises every report into labelled sections with descriptions.
4.  Creates outputs/reports_bundle.zip for one-click download.

Run at the end of any pipeline session:

    python scripts/bundle_reports.py
    python scripts/bundle_reports.py --outputs-dir /path/to/outputs
"""

from __future__ import annotations

import argparse
import html as _html
import json
import shutil
import sys
import zipfile
from datetime import datetime, timezone
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

# ---------------------------------------------------------------------------
# Report catalogue
# ---------------------------------------------------------------------------
# (relative path from outputs/, title, section, one-line description)

_CATALOGUE: list[tuple[str, str, str, str]] = [
    # ── Mission Control ─────────────────────────────────────────────────────
    (
        "final_report.html",
        "Pipeline Final Report",
        "mission_control",
        "Consolidated §1–§9 report: calendar, reading direction, compounds, "
        "hypothesis convergence, deity search, decipherment ranking, new anchors, "
        "sign 600 diagnostic, holy-grail update.",
    ),
    (
        "decipherment/holy_grail_report.html",
        "Holy-Grail Passage Report",
        "mission_control",
        "Pre/post-contact key-change analysis for P007 and P012. The two "
        "confirmed Kasiski key-change events — the central cryptanalytic finding.",
    ),
    # ── Decipherment ────────────────────────────────────────────────────────
    (
        "decipherment/decipherment_report.html",
        "MCMC Decipherment Ranking",
        "decipherment",
        "Ranked H0001–H0005 hypotheses with phoneme assignments, per-stratum "
        "LM scores, beam scores, and MCMC posterior confidence per sign.",
    ),
    (
        "self_training/self_training_report.html",
        "Ensemble Self-Training Report",
        "decipherment",
        "Iteration-by-iteration anchor promotion log: which signs graduated "
        "from soft to hard cribs, score trajectory, convergence verdict.",
    ),
    # ── Calendar & Gloss ────────────────────────────────────────────────────
    (
        "analysis/calendar_gloss_validation.html",
        "Calendar Gloss Validation",
        "calendar_gloss",
        "Mamari Ca6–Ca9 lunar vocabulary lift (4.9×) and night-alignment "
        "coherence for H0001 phoneme assignments.",
    ),
    (
        "analysis/gloss_report.html",
        "Hypothesis Gloss Report",
        "calendar_gloss",
        "IDS/Thomson lexicon lookups for every sign in the top hypotheses, "
        "ranked by tier (EXACT → HIGH → MEDIUM).",
    ),
    (
        "analysis/hypothesis_comparison.html",
        "Hypothesis Convergence",
        "calendar_gloss",
        "Position-by-position comparison of H0001–H0005 across all 146 "
        "Mamari calendar signs. 83.6% full agreement.",
    ),
    (
        "analysis/deity_name_search.html",
        "Deity Name Search (Phoneme)",
        "calendar_gloss",
        "Permutation test for Polynesian deity name phoneme sequences "
        "(makemake, tangaroa, …). Null result (p=1.00) — rules out "
        "phonetic encoding, supports logographic hypothesis.",
    ),
    (
        "analysis/deity_logographic_600.html",
        "Sign 600 Logographic Analysis",
        "calendar_gloss",
        "Logographic deity confidence score for sign 600 (Tangata Manu): "
        "Tablet D specificity, P007 presence, position bias, calendar co-occurrence.",
    ),
    (
        "analysis/compound_compositionality.html",
        "Compound Compositionality",
        "calendar_gloss",
        "Compound glyphs that decompose into phoneme sequences matching "
        "IDS/Thomson lexicon entries — validates two assignments simultaneously.",
    ),
    # ── Passage Reports ─────────────────────────────────────────────────────
    (
        "analysis/passage_reports/index.html",
        "Parallel Passages — Index",
        "passages",
        "Index of all 13 multi-tablet parallel passages with diachronic "
        "change summary, attestation counts, and holy-grail flags.",
    ),
    (
        "analysis/passage_reports/P007_ADHS.html",
        "P007 — Holy Grail (Tablets A/D/H/S)",
        "passages",
        "Canonical ['007','600','007','010']. Confirmed pre/post-contact "
        "key-change event. Sign 600 never omitted.",
    ),
    (
        "analysis/passage_reports/P012_ABCDEGHINPQSX.html",
        "P012 — Holy Grail (11 tablets)",
        "passages",
        "Second confirmed key-change event. Widest attestation (11 tablets). "
        "Strongest cross-stratum diachronic signal.",
    ),
    # ── Zone B: Structural Analysis ─────────────────────────────────────────
    (
        "analysis/entropy_report.html",
        "Entropy & Information Theory",
        "zone_b_structural",
        "Parts I–III: IC / entropy statistics, reading direction tests 1–7 "
        "(cross-side PPL, LTOO, recto/verso MI), tablet spectrum.",
    ),
    (
        "analysis/compound_report.html",
        "Compound Glyph Detection",
        "zone_b_structural",
        "UMAP cluster anomalies + positional profiling for compound glyphs. "
        "Ranked candidates with iconographic disambiguation.",
    ),
    (
        "analysis/reading_order_report.html",
        "Reading Order Tests (Basic)",
        "zone_b_structural",
        "Tests 3–4: line boundary entropy, recto/verso ordering.",
    ),
    (
        "analysis/reading_order_v2_report.html",
        "Reading Order Tests v2",
        "zone_b_structural",
        "Tests 1–7 including cross-side PPL (strongest signal: margin 0.12), "
        "LTOO per-tablet, recto/verso mutual information.",
    ),
    (
        "analysis/spectrum_report.html",
        "Tablet Spectrum Report",
        "zone_b_structural",
        "Logographic ↔ syllabic spectrum score for all tablets. "
        "Tablet D occupies the most syllabic end.",
    ),
    (
        "analysis/pozdniakov_report.html",
        "Pozdniakov Paradigmatic Analysis",
        "zone_b_structural",
        "Automated replication of Pozdniakov (1996/2011) paradigmatic equivalence classes. "
        "Sign substitution pairs from parallel passages, union-find grouping, "
        "recall/precision/F1 vs reference classes, and MCMC cross-validation.",
    ),
    (
        "analysis/pozdniakov_hypothesis_report.html",
        "Pozdniakov Hypothesis Tests",
        "zone_b_structural",
        "Independent replication of Pozdniakov (1996/2011) morpheme "
        "identification tests against the corpus.",
    ),
    (        "analysis/contact_partition_report.html",
        "Contact Partition Report",
        "zone_b_structural",
        "G\u00b2 bipartite sign-frequency partition with Bonferroni correction. "
        "Stratum-shifting signs (pre- vs post-contact), stable signs, "
        "and p-values for 120 signs \u00d7 2 strata comparisons.",
    ),
    (        "contact_partition_bipartite.html",
        "Contact Partition (Bipartite)",
        "zone_b_structural",
        "G² bipartite graph of pre- vs post-contact sign frequency differences. "
        "Identifies signs that shift stratum.",
    ),
    # ── Zone A: Visual / Embedding ──────────────────────────────────────────
    (
        "analysis/embedding_report.html",
        "Embedding Report",
        "zone_a_visual",
        "Zone A autoencoder UMAP clusters vs Barthel families. "
        "ARI and per-cluster glyph sample.",
    ),
    (
        "analysis/astronomical_report.html",
        "Astronomical Glyph Candidates",
        "zone_a_visual",
        "Signs flagged by multiple methods (IC, positional, UMAP) as potential "
        "astronomical markers. Includes Dietrich catalogue cross-reference.",
    ),
]

# Section metadata
_SECTIONS: dict[str, tuple[str, str]] = {
    "mission_control": (
        "Mission Control",
        "The two consolidated reports — start here for the full cryptanalytic picture.",
    ),
    "decipherment": (
        "Decipherment",
        "MCMC phoneme hypothesis ranking and self-training anchor promotion logs.",
    ),
    "calendar_gloss": (
        "Calendar & Gloss Analysis",
        "Mamari calendar alignment, hypothesis comparison, deity search, "
        "and compound compositionality.",
    ),
    "passages": (
        "Parallel Passages",
        "Individual report for each of the 13 multi-tablet passages "
        "identified by the Kasiski-equivalent search.",
    ),
    "zone_b_structural": (
        "Zone B — Structural Analysis",
        "Entropy, reading direction, compound detection, tablet spectrum, "
        "Pozdniakov tests, and contact-era stratification.",
    ),
    "zone_a_visual": (
        "Zone A — Visual & Embedding",
        "Autoencoder UMAP clusters, astronomical candidates, "
        "and divergence analysis.",
    ),
    "other": (
        "Other Reports",
        "Reports discovered in the outputs tree that are not in the main catalogue.",
    ),
}

_SECTION_ORDER = [
    "mission_control",
    "decipherment",
    "calendar_gloss",
    "passages",
    "zone_b_structural",
    "zone_a_visual",
    "other",
]

# ---------------------------------------------------------------------------
# CSS + HTML
# ---------------------------------------------------------------------------

_CSS = """\
:root {
  --bg: #0d0f12; --surface: #161920; --surface2: #1e2229;
  --border: #2a2e38; --text: #d0d4dc; --muted: #6b7280;
  --accent: #c4a96d; --green: #4ade80; --red: #f87171;
  --blue: #93c5fd; --yellow: #facc15;
}
* { box-sizing: border-box; margin: 0; padding: 0; }
html { scroll-behavior: smooth; }
body {
  background: var(--bg); color: var(--text);
  font-family: 'JetBrains Mono', monospace; font-size: 13px; line-height: 1.65;
}
a { color: var(--accent); text-decoration: none; }
a:hover { text-decoration: underline; }

.wrap { max-width: 1060px; margin: 0 auto; padding: 52px 28px 80px; }

/* ── Header ── */
.header {
  border-bottom: 1px solid var(--border);
  padding-bottom: 32px; margin-bottom: 48px;
}
.title { font-size: 26px; font-weight: 600; color: var(--accent); letter-spacing: -.3px; }
.subtitle { color: var(--muted); font-size: 11px; margin-top: 6px; }
.meta-row {
  display: flex; gap: 24px; flex-wrap: wrap;
  margin-top: 20px; font-size: 11px; color: var(--muted);
}
.meta-row b { color: #aaa; }

/* ── Section ── */
.section { margin-bottom: 48px; }
.section-title {
  font-size: 14px; font-weight: 600; color: var(--text);
  border-bottom: 1px solid var(--border);
  padding-bottom: 8px; margin-bottom: 6px;
}
.section-desc { font-size: 11px; color: var(--muted); margin-bottom: 16px; }

/* ── Report card ── */
.report-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
  gap: 12px;
}
.report-card {
  background: var(--surface); border: 1px solid var(--border);
  border-radius: 6px; padding: 16px 18px;
  transition: border-color .15s;
}
.report-card:hover { border-color: var(--accent); }
.report-card.missing {
  opacity: 0.45; border-style: dashed;
}
.report-name {
  font-size: 13px; font-weight: 600; color: var(--accent);
  margin-bottom: 5px;
}
.report-desc {
  font-size: 10.5px; color: var(--muted); line-height: 1.6;
  margin-bottom: 10px;
}
.report-footer {
  display: flex; align-items: center; gap: 10px;
  font-size: 10px; color: var(--muted);
}
.report-size { color: #6b7280; }
.open-btn {
  display: inline-block; padding: 3px 10px;
  background: rgba(196,169,109,.12); color: var(--accent);
  border: 1px solid rgba(196,169,109,.3); border-radius: 3px;
  font-size: 10px; cursor: pointer;
}
.open-btn:hover { background: rgba(196,169,109,.22); text-decoration: none; }
.missing-tag {
  font-size: 10px; color: var(--muted); font-style: italic;
}

/* ── Nav sidebar (toc) ── */
.toc {
  position: fixed; top: 40px; right: 28px;
  background: var(--surface); border: 1px solid var(--border);
  border-radius: 6px; padding: 12px 16px;
  max-width: 200px; font-size: 10px;
}
.toc-title { color: var(--muted); margin-bottom: 8px; font-size: 9px; text-transform: uppercase; }
.toc a { display: block; color: var(--muted); padding: 2px 0; }
.toc a:hover { color: var(--accent); }

@media (max-width: 1300px) { .toc { display: none; } }
"""

_SECTION_ACCENT: dict[str, str] = {
    "mission_control": "var(--red)",
    "decipherment":    "var(--accent)",
    "calendar_gloss":  "var(--yellow)",
    "passages":        "var(--blue)",
    "zone_b_structural": "var(--green)",
    "zone_a_visual":   "#c084fc",
    "other":           "var(--muted)",
}


def _format_size(path: Path) -> str:
    if not path.exists():
        return ""
    kb = path.stat().st_size / 1024
    if kb >= 1024:
        return f"{kb/1024:.1f} MB"
    return f"{kb:.0f} KB"


def _render_card(
    rel_path: str,
    title: str,
    desc: str,
    bundle_root: Path,
) -> str:
    physical = bundle_root / rel_path
    exists = physical.exists()
    size_str = _format_size(physical) if exists else ""

    card_cls = "report-card" if exists else "report-card missing"
    link_html = (
        f'<a class="open-btn" href="{_html.escape(rel_path)}" target="_blank">Open ↗</a>'
        if exists else
        '<span class="missing-tag">not generated this run</span>'
    )
    return (
        f'<div class="{card_cls}">'
        f'<div class="report-name">{_html.escape(title)}</div>'
        f'<div class="report-desc">{_html.escape(desc)}</div>'
        f'<div class="report-footer">'
        f'<span class="report-size">{_html.escape(size_str)}</span>'
        f'{link_html}'
        f'</div>'
        f'</div>'
    )


def build_index(
    bundle_root: Path,
    catalogued: list[tuple[str, str, str, str]],
    extras: list[Path],
    generated: str,
    n_total: int,
) -> str:
    # Count what actually exists
    n_present = sum(1 for path, *_ in catalogued if (bundle_root / path).exists())
    n_present += len(extras)

    # TOC
    toc_links = "\n".join(
        f'<a href="#{sid}">{_html.escape(_SECTIONS[sid][0])}</a>'
        for sid in _SECTION_ORDER
        if any(s == sid for _, _, s, _ in catalogued) or (sid == "other" and extras)
    )

    # Group catalogue by section
    by_section: dict[str, list[tuple[str, str, str]]] = {s: [] for s in _SECTION_ORDER}
    for path, title, section, desc in catalogued:
        by_section.setdefault(section, []).append((path, title, desc))

    # Extras in "other"
    for p in sorted(extras):
        rel = str(p.relative_to(bundle_root)).replace("\\", "/")
        by_section["other"].append((rel, p.stem.replace("_", " ").title(), ""))

    sections_html = ""
    for sid in _SECTION_ORDER:
        items = by_section.get(sid, [])
        if not items:
            continue
        sec_title, sec_desc = _SECTIONS[sid]
        accent = _SECTION_ACCENT.get(sid, "var(--accent)")
        cards = "\n".join(_render_card(path, title, desc, bundle_root) for path, title, desc in items)
        sections_html += (
            f'<div class="section" id="{sid}">'
            f'<div class="section-title" style="border-color:{accent}">'
            f'{_html.escape(sec_title)}</div>'
            f'<div class="section-desc">{_html.escape(sec_desc)}</div>'
            f'<div class="report-grid">{cards}</div>'
            f'</div>'
        )

    return f"""\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Rongorongo — Pipeline Report Index</title>
<style>{_CSS}</style>
</head>
<body>
<nav class="toc">
  <div class="toc-title">Sections</div>
  {toc_links}
</nav>
<div class="wrap">
  <div class="header">
    <div class="title">Rongorongo Decipherment Pipeline</div>
    <div class="subtitle">Report bundle — open any report to review findings</div>
    <div class="meta-row">
      <span><b>Generated</b> {_html.escape(generated)}</span>
      <span><b>Reports present</b> {n_present} / {n_total}</span>
      <span><b>Bundle</b> reports_bundle.zip</span>
    </div>
  </div>
  {sections_html}
</div>
</body>
</html>
"""


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def bundle(outputs_dir: Path) -> Path:
    """Build the bundle. Returns path to the .zip file."""
    bundle_root = outputs_dir / "reports_bundle"
    if bundle_root.exists():
        shutil.rmtree(bundle_root)
    bundle_root.mkdir(parents=True)

    # Track which relative paths we've copied (to detect extras)
    catalogued_relpaths = {entry[0] for entry in _CATALOGUE}
    copied_relpaths: set[str] = set()

    # Copy catalogued reports (preserving sub-paths)
    for rel_path, *_ in _CATALOGUE:
        src = outputs_dir / rel_path
        dest = bundle_root / rel_path
        dest.parent.mkdir(parents=True, exist_ok=True)
        if src.exists():
            shutil.copy2(src, dest)
            copied_relpaths.add(rel_path)

    # Copy all other HTMLs found in outputs/ that aren't in the catalogue
    extras: list[Path] = []
    for src in sorted(outputs_dir.rglob("*.html")):
        rel = str(src.relative_to(outputs_dir)).replace("\\", "/")
        if rel in catalogued_relpaths or "reports_bundle" in rel:
            continue
        dest = bundle_root / rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dest)
        extras.append(bundle_root / rel)

    # Generate index
    generated = datetime.now(tz=timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    n_total = len(_CATALOGUE) + len(extras)
    index_html = build_index(bundle_root, _CATALOGUE, extras, generated, n_total)
    (bundle_root / "index.html").write_text(index_html, encoding="utf-8")

    # Zip the bundle
    zip_path = outputs_dir / "reports_bundle.zip"
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for f in sorted(bundle_root.rglob("*")):
            if f.is_file():
                zf.write(f, f.relative_to(bundle_root))
    return zip_path


def main() -> None:
    p = argparse.ArgumentParser(description="Bundle all pipeline HTML reports for download.")
    p.add_argument(
        "--outputs-dir", type=Path,
        default=PROJECT_ROOT / "outputs",
        help="Root outputs directory (default: outputs/)",
    )
    args = p.parse_args()

    if not args.outputs_dir.exists():
        print(f"outputs dir not found: {args.outputs_dir}")
        sys.exit(1)

    print("Bundling reports…")
    zip_path = bundle(args.outputs_dir)

    bundle_root = args.outputs_dir / "reports_bundle"
    all_html = sorted(bundle_root.rglob("*.html"))
    total_kb = zip_path.stat().st_size / 1024

    print(f"\n{'━'*60}")
    print(f"  Report bundle complete")
    print(f"  {len(all_html)} HTML files  ({total_kb:.0f} KB zipped)")
    print(f"  Index:  {bundle_root}/index.html")
    print(f"  Zip:    {zip_path}")
    print(f"{'━'*60}")
    print("\n  Open index.html or download reports_bundle.zip")


if __name__ == "__main__":
    main()
